services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file: 
      - .env
    environment:
      - NODE_ENV=development 
      - PORT=5010 
    volumes:
      - ./backend:/usr/src/app/backend
    depends_on:
      - mongo 
    restart: unless-stopped

  mongo:
    image: mongo:latest 
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 
    restart: unless-stopped

volumes:
  mongo-data: 
    driver: local